default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: myapp_development
  host: db
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  
test:
  <<: *default
  database: myapp_test
  host: db
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  
production:
  <<: *default
  database: myapp_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock

