default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>
  username: <%= ENV['MYSQL_USERNAME'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] || '' %>

development:
  <<: *default
  database: myapp_development
  host: db
  username: root
  password: password
  
test:
  <<: *default
  database: myapp_test
  host: db
  username: root
  password: password
  
production:
  <<: *default
  database: myapp_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] || ENV['MYSQL_PASSWORD']%>
  socket: /var/lib/mysql/mysql.sock

